# Generated by Django 5.1.7 on 2026-05-10 16:56

import django.db.models.deletion
import quotes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_alter_quote_expires_at_alter_quote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='expires_at',
            field=models.DateTimeField(default=quotes.models.get_default_expiration),
        ),
        migrations.CreateModel(
            name='QuoteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='quotes.quote')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
    ]
